from enum import Enum

class ActionEnum(Enum):
        EXECUTE_LINEAR_REGRESSION = "EXECUTE_LINEAR_REGRESSION"
        GET_STH_COMET_DATA = "GET_STH_COMET_DATA"
        EXECUTE_CORRELATION_ANALYSIS = "EXECUTE_CORRELATION_ANALYSIS"
        SEND_RESPONSE_TO_API_GATEWAY = "SEND_RESPONSE_TO_API_GATEWAY"
        SEND_ASYNC_RESPONSE_TO_API_GATEWAY = "SEND_ASYNC_RESPONSE_TO_API_GATEWAY"