import enum


class ActionEnum(enum):
    EXECUTE_LINEAR_REGRESSION = "EXECUTE_LINEAR_REGRESSION"
    GET_STH_COMET_DATA = "GET_STH_COMET_DATA"
    EXECUTE_CORRELATION_ANALYSIS = "EXECUTE_CORRELATION_ANALYSIS"