from enum import Enum


class ApiActionsEnum(Enum):
    CORRELATION_ANALYSIS = "CORRELATION_ANALYSIS"
    LINEAR_REGRESSION_ANALYSIS = "LINEAR_REGRESSION_ANALYSIS"
    TWO_DIMENSIONAL_GRAPHIC = "2D_GRAPHIC"