version: '3'
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    #hostname: rabbitmq
    ports:
      - "5672:5672"  # Porta padrão para conexões RabbitMQ
      - "15672:15672"  # Porta da interface de gerenciamento do RabbitMQ (opcional)
   
  app:
    build:
      context: .  # Substitua pelo caminho para o diretório da sua aplicação Python
    ports:
      - "5000:5000"  # Substitua pela porta da sua aplicação Python
    depends_on:
      - rabbitmq
    environment:
      - INTERNAL_RABBIT_MQ_HOST=rabbitmq
      - INTERNAL_RABBIT_MQ_PORT=5672
      - STH_COMET_HOST=172.26.64.1
      - STH_COMET_PORT=8666
      - ORION_CONTEXT_BROKER_HOST=172.26.64.1
      - ORION_CONTEXT_BROKER_PORT=1026
      - FIWARE_SERVICE=smart
      - FIWARE_SERVICE_PATH=/

