version: '3'
services:

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    command: bash -c "rabbitmq-plugins enable --offline rabbitmq_web_stomp && rabbitmq-server"
    ports:
      - "5672:5672"  
      - "15672:15672"  
      - "15674:15674"

    volumes:
      - ./dados:/var/lib/rabbitmq
    
  app:
    build:
      context: .  
    ports:
      - "5000:5000"  
    depends_on:
      - rabbitmq
    environment:
      - INTERNAL_RABBIT_MQ_HOST=rabbitmq
      - INTERNAL_RABBIT_MQ_PORT=5672
      - STH_COMET_HOST=172.26.64.1
      - STH_COMET_PORT=8666
      - ORION_CONTEXT_BROKER_HOST=172.26.64.1
      - ORION_CONTEXT_BROKER_PORT=1026
      - FIWARE_SERVICE=smart
      - FIWARE_SERVICE_PATH=/

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"